export const environment = {
  VERSION: require('../../package.json').version,
  production: true,
  autoLogin: false,

  // urlSecurity: 'http://172.16.34.6/PosSeguridadMilano',
  // urlServices: 'http://172.16.34.6/PosServiciosMIlano',
  // urlUpdateVersion: 'http://172.16.34.6/PosActualizadorMilano',

  //urlSecurity: 'http://localhost:30972', // OCG: Proyecto Project.ServicesSecurityWCF
  urlSecurity: 'http://localhost:30980', // OCG: Proyecto Project.ServicesSecurityWCF
  urlServices: 'http://localhost:30980', // OCG: Proyecto Project.Services
  urlUpdateVersion: 'http://localhost:63270', // OCG: Proyecto Project.POSUpdaterServices
  posversion: 'v1.4.0',

  loginPath: '/Login/LoginService.svc/login',
  logoutPath: '/Login/LogoutService.svc/logout',
  versionSeg: '/Login/LoginService.svc/versionSeguridad',
  versionServ: '/Login/LoginService.svc/versionServicios',
  verificaSoftware: '/Login/LoginService.svc/versionSoftware',
  validacionUsuarioPath: '/Security/SecurityService.svc/validacionUsuario',
  configGeneralesCajaTiendaPath: '/General/ConfigGeneralesCajaTiendaService.svc/getConfiguration',
  productoServicesPath: '/General/ProductServices.svc/getProduct',
  employeePath: '/Sales/EmployeeService.svc/getEmployee',
  companiasPath: '/General/PagoServiciosService.svc/empresasTA',
  montosPath: '/General/PagoServiciosService.svc/empresasTA',
  serviciosPath: '/General/PagoServiciosService.svc/empresasServicios',
  validacionTAPath: '/Sales/FraudValidationService.svc/fraudValidation',
  catProveedoresPath: '/Catalogs/CatologoServicio.svc/proveedores',
  catEstiloPath: '/Catalogs/CatologoServicio.svc/estilos',
  catDepartamentosPath: '/Catalogs/CatologoServicio.svc/departamentos',
  catSubdepartamentosPath: '/Catalogs/CatologoServicio.svc/subDepartamentos',
  catClasesPath: '/Catalogs/CatologoServicio.svc/clases',
  catSubclasesPath: '/Catalogs/CatologoServicio.svc/subClases',
  busquedaAvanzadaPath: '/General/ProductServices.svc/getProductAdvanced',
  almacenarImagenRemotaPath: '/General/GeneralService.svc/almacenarImagenRemota',
  totalizarVentaPath: '/Sales/SalesService.svc/totalizarVenta',
  cerrarDevolucionPath: '/Sales/SalesService.svc/cerrarDevolucionSinPagos',
  totalizarApartadoPath: '/Apartados/ApartadoService.svc/apartadoTotalizar',
  getEmployeeMilanoPath: '/Sales/EmployeeService.svc/getEmployeeMilano',
  validaVentaEmpleadoPath: '/Sales/SalesService.svc/validarVentaEmpleado',
  getTarjetaRegaloPath: '/General/ProductServices.svc/getTarjetaRegalo',
  finalizarVentaPath: '/Sales/SalesService.svc/finalizarVenta',
  pagoEfectivoPath: '/Sales/PaymentProcessingService.svc/procesarMovimientoEfectivo',
  anularEfectivoPath: '/Sales/PaymentProcessingService.svc//anularMovimientoEfectivo',
  pagoValesPath: '/Sales/PaymentProcessingService.svc/procesarMovimientoVales',
  clienteRequestPath: '/Sales/SalesService.svc/clientes',
  clienteModificaPath: '/Sales/SalesService.svc/altaClientes',
  mayoristaRequestPath: '/Sales/SalesService.svc/busquedaMayoristas',
  mayoristaDetalleRequestPath: '/Sales/SalesService.svc/pagoMayoristas',
  cancelarPath: '/Catalogs/ReasonsCodesService.svc/getReasonCode',
  anularTransaccionPath: '/Sales/SalesService.svc/anularVenta',
  cancelacionApartadoPath: '/Apartados/ApartadoService.svc/apartadoCancelar/',
  plazosApartadoPath: '/Apartados/ApartadoService.svc/diasVencimiento',
  crearApartadoPath: '/Apartados/ApartadoService.svc/apartadoFinalizar',
  abonoApartadoPath: '/Apartados/ApartadoService.svc/apartadoAbonar',
  busquedaApartadoPath: '/Apartados/ApartadoService.svc/apartadoBuscar',
  suspenderTransaccionPath: '/Sales/SalesService.svc/suspenderVenta',
  buscarTransaccionPath: '/Sales/SalesService.svc/getTransacciones',
  getVentaPath: '/Sales/SalesService.svc/venta/',
  consultaSaldoMMPath: '/MM/MelodyMilanoService.svc/consultarInformacionTCMM',
  getConvertirDivisaPath: '/General/GeneralService.svc/convertirDivisa',
  reimprimirTicket: '/General/ImprimirTicketService.svc/imprimirTicket/',
  postAnularVentaPath: '/Sales/SalesService.svc/postAnularVenta',
  changePasswordPath: '/Security/SecurityService.svc/changePassword',
  finalizarPagoTCMMPath: '/MM/MelodyMilanoService.svc/finalizarPagoTCMM',
  procesarMovimientoTarjetaRegaloPath: '/Sales/PaymentProcessingService.svc/procesarMovimientoTarjetaRegalo',
  procesarMovimientoPagoVentaEmpleadoPath: '/Sales/PaymentProcessingService.svc/procesarMovimientoPagoVentaEmpleado',
  procesarMovimientoPagoTarjetaPath: '/Sales/PaymentProcessingService.svc/procesarMovimientoTarjetaBancariaAmericanExpress',
  procesarMovimientoPagoTarjetaVisaMasterPath: '/Sales/PaymentProcessingService.svc/procesarMovimientoTarjetaBancariaVisaMaster',
  procesarMovimientoTarjetaBancariaCashBack: '/Sales/PaymentProcessingService.svc/procesarMovimientoTarjetaBancariaCashBack',
  procesarMovimientoTarjetaBancariaCashBackAdvance: '/Sales/PaymentProcessingService.svc/procesarMovimientoTarjetaBancariaCashBackAdvance',
  procesarMovimientoTarjetaBancariaConPuntos: '/Sales/PaymentProcessingService.svc/procesarMovimientoTarjetaBancariaConPuntos',
  procesarMovimientoTarjetaBancariaCancelar: '/Sales/PaymentProcessingService.svc/procesarMovimientoTarjetaBancariaCancelar',
  postVentaDolares: '/General/GeneralService.svc/ventaDolares', // OCG EndPoint de punto clave para venta de dolares
  /* Se le envían los datos del ticket y partida que se pago con TCMM
 para que se haga el descuento de la tarjeta y se quede registrado ese pago.
 Nota: No finaliza la venta*/
  procesarMovimientoTarjetaMM: '/MM/MelodyMilanoService.svc/finalizarCompraTCMM',

  obtenerTarjetaMM: '/Sales/PaymentProcessingService.svc/obtenerTarjetaBancariaMelody',
  procesarMovimientoMayoristaPath: '/Sales/PaymentProcessingService.svc/procesarMovimientoMayorista',
  busquedaClienteFinalPath: '/Catalogs/CatologoServicio.svc/busquedaClienteFinal',
  altaClienteFinalPath: '/Catalogs/CatologoServicio.svc/altaClienteFinal',
  getDivisasPath: '/Catalogs/CatologoServicio.svc/divisas',
  agregarLineaTicketVenta: '/Sales/SalesService.svc/AgregarLineaTicketVenta',
  cambiarPiezasLineaTicketVenta: '/Sales/SalesService.svc/cambiarPiezasLineaTicketVenta',
  eliminarLineaTicketVenta: '/Sales/SalesService.svc/eliminarLineaTicketVenta',
  cambiarPrecioLineaTicketVenta: '/Sales/SalesService.svc/cambiarPrecioLineaTicketVenta',
  agregarLineaTicketApartado: '/Apartados/ApartadoService.svc/agregarLineaTicketApartado',
  cambiarPiezasLineaTicketApartado: '/Apartados/ApartadoService.svc/cambiarPiezasLineaTicketApartado',
  eliminarLineaTicketApartado: '/Apartados/ApartadoService.svc/eliminarLineaTicketApartado',
  cambiarPrecioLineaTicketApartado: '/Apartados/ApartadoService.svc/cambiarPrecioLineaTicketApartado',
  descuentoDirectoVenta: '/Sales/DescuentosDevolucionesService.svc/descuentoDirectoVenta',
  anularApartado: '/Apartados/ApartadoService.svc/anularApartado',
  retiroParcialEfectivoPath: '/General/EgresosService.svc/retiroParcialEfectivo',
  egresoPath: '/General/EgresosService.svc/egreso',
  pagoServiciosOpciones: '/Sales/SalesService.svc/pagoServiciosOpciones',

  // Obtiene el plazo a meses de financieamiento de TCMM
  planesFinanciamiento: '/MM/MelodyMilanoService.svc/consultarPlanesFinanciamientoDescuentoPrimeraCompra',

  mercanciaDaniadaPath: '/Sales/DescuentosDevolucionesService.svc/descuentoMercanciaDaniada',
  picosMercanciaPath: '/Sales/DescuentosDevolucionesService.svc/descuentoMercanciaPico',
  totalVentasPath: '/Reportes/ReporteService.svc/ventasDepartamento',
  lecturaXPath: '/General/LecturaService.svc/obtenerTotalesFormaPago',
  getValesPath: '/Catalogs/FormaPagoService.svc/getTiposVale',
  ignorarRetiroPath: '/General/EgresosService.svc/ignorarRetiro',
  getDenominacionesPath: '/General/LecturaService.svc/obtenerDenominaciones',
  ejecutarArqueoCajaPath: '/General/LecturaService.svc/ejecutarArqueoCaja',
  ejecutarCorteCajaPath: '/General/LecturaService.svc/ejecutarCorteCaja',
  eliminarLineaMayorista: '/Sales/SalesService.svc/eliminarLineaMayorista',
  ventasVendedorPath: '/Reportes/ReporteService.svc/ventasVendedor',
  ventasSkuPath: '/Reportes/ReporteService.svc/ventasSKU',
  ventasCajaPath: '/Reportes/ReporteService.svc/ventasCaja',
  ventasHrPath: '/Reportes/ReporteService.svc/ventasPorHora',
  ventasDetallePath: '/Reportes/ReporteService.svc/apartadosDetalle',
  ventasSinDetallePath: '/Reportes/ReporteService.svc/apartadosSinDetalle',
  devolucionesSKUPath: '/Reportes/ReporteService.svc/devolucionesSKU',
  ingresosEgresosPath: '/Reportes/ReporteService.svc/ingresosEgresos',
  validarDevolucionPatch: '/Sales/DescuentosDevolucionesService.svc/validarDevolucion/',
  cambiarPiezasArticuloLineaTicketDevolucionPath: '/Sales/DescuentosDevolucionesService.svc/cambiarPiezasArticuloLineaTicketDevolucion',
  cargarLlavesPath: '/Sales/PaymentProcessingService.svc/cargarLlaves',
  procesarMovimientoNotaCreditoPath: '/Sales/PaymentProcessingService.svc/procesarMovimientoNotaCredito',
  procesarMovimientoPagoPinPadMovilPath: '/Sales/PaymentProcessingService.svc/procesarMovimientoPagoPinPadMovil',
  inicioDiaPath: '/InicioFinDia/InicioFinDiaService.svc/iniciarDia',
  capturaLuzPath: '/InicioFinDia/CapturaLuzService.svc/capturarLuzInicioDia',
  autenticacionOfflinePath: '/InicioFinDia/AutenticacionOfflineService.svc/autenticacionOffline',
  finDiaPath: '/InicioFinDia/InicioFinDiaService.svc/finalizarDia',
  capturaLuzFinPath: '/InicioFinDia/CapturaLuzService.svc/capturarLuzFinDia',
  confimacionFinDia: '/InicioFinDia/CapturaLuzService.svc/confirmacionFinDia',
  cashOutPath: '/InicioFinDia/InicioFinDiaService.svc/obtenCashOut',
  actualizarCashOutPath: '/InicioFinDia/InicioFinDiaService.svc/actualizarCashOut',
  actualizarRelacionCajaPath: '/InicioFinDia/InicioFinDiaService.svc/actualizarRelacionCajaFinDia',
  lecturaZFinDiaPath: '/InicioFinDia/InicioFinDiaService.svc/ejecutarLecturaZLogoutOffline',
  lecturaZOfflinePath: '/General/LecturaService.svc/obtenerTotalesFormaPagoCaja',
  validaValePath: '/Finlag/FinlagService.svc/validaVale',
  consultaClienteFinLagPath: '/Finlag/FinlagService.svc/consultaCliente',
  tablaAmortizacionPath: '/Finlag/FinlagService.svc/obtenerTablaAmortizacion',
  aplicarValePath: '/Finlag/FinlagService.svc/procesarMovimientoAplicarValeFinlag',
  redencionCuponesPath: '/Sales/PaymentProcessingService.svc/procesarMovimientoRedencionCuponPromocional',
  reporteRelacionCajaPath: '/Reportes/ReporteService.svc/relacionCaja',
  reimprimirRelacionCajaPath: '/General/ImprimirTicketService.svc/imprimirRelacionCaja',
  autenticacionLecturaPath: '/InicioFinDia/InicioFinDiaService.svc/validarLecturaZLogoutOffline',
  comprobarVersionPath: '/Updater/ActualizadorVersionService.svc/local/comprobarVersionSoftwareActual',
  actualizarVersionSoftwarePath: '/Updater/ActualizadorVersionService.svc/local/actualizarVersionSoftware',
  estatusVersionSoftwarePath: '/Updater/ActualizadorVersionService.svc/local/estatusActualizacionVersionSoftware',
  solicitudDescuentoPath: '/Sales/SalesService.svc/solicitudAutorizacion',
  procesarMovimientoPagoTransferenciaPath: '/Sales/PaymentProcessingService.svc/procesarMovimientoPagoTransferencia',
  autorizaCancelacionTransaccion: '/Sales/SalesService.svc/autorizaCancelacionTransaccion',
  verificarPagoWeb: '/Sales/SalesService.svc/verificarPagoWeb/', // OCG Validar folio para pago Web
  //consultaPagoWebx: 'https://credito.milano.com.mx/apishopify/api/Order/PaymentInf/'
  //solicitudDescuentoPath: '/Sales/SalesService.svc/SolicitudAutorizacionDescuento'
  //solicitudDescuentoPath: 'http://localhost:42758/InfoDescuento.asmx/getAutorization'
  enpObtenerMSI: '/Sales/PaymentProcessingService.svc/obtenerConfiguracionMsi',
  epointReadCard: '/Sales/PaymentProcessingService.svc/api/readCard',
  epointCompleteSale: '/Sales/PaymentProcessingService.svc/api/completeSale',

  postLealtad: '/Finlag/FinlagService.svc/registrolealtad',
  postConsultaLealtad: '/Finlag/FinlagService.svc/consultalealtad',
};


